### ISSUE TITLE
CST816S datasheet

### ISSUE THREAD

**Issue by nicogou** [mjdonders/CST816_TouchLib#11]
Hello,
Do you have the CST816S Data Reference document which lists all the addresses and technical information ? All the documents I have found so far are very lackluster
Thanks

**Comment by tyeth** [comment]
Looks like this open PR has the link you need. https://github.com/mjdonders/CST816_TouchLib/pull/9/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R23

The datasheets are from the T-DisplayS3 repo: https://github.com/Xinyuan-LilyGO/T-Display-S3/tree/main/datasheet

**Comment by tyeth** [comment]
Here's googles translated version:
[CST816S_English-20190508.pdf](https://github.com/mjdonders/CST816_TouchLib/files/14151590/CST816S_English-20190508.pdf)

**Comment by mjdonders** [comment]
Sorry for the delay in this. Yes tyeth pointed you to the same I have also used for the finalization. I however think that this is still extremely limited..

**Comment by tyeth** [comment]
Hey @mjdonders, I agree, maybe we can leave this open in the hope someone provides a more complete version in the future.
