### ISSUE TITLE
Missing release events when using setNotifyOnMovement

### ISSUE THREAD

**Issue by rhueppin** [mjdonders/CST816_TouchLib#12]
When using `setNotifyOnMovement`, release events for gestures are missing if they appear less than 50 ms after the last move event because **all** gesture events are suppressed for 50 ms. As a quick fix I added `&& currentlyPressed` to the if statement in lines 336 to 339. For me it seems to work now, but I don't know if there are side effects when other values in this if statement are set...

**Comment by mjdonders** [comment]
Good point, thanks.
I'm currently updating the library for the T-Display S3 AMOLED, which has a slightly different touch controller chip.
With the release for that I'll update the code as per your suggestion.
