### ISSUE TITLE
I want to know about connect cst816 to nrf5340

### ISSUE THREAD

**Issue by smith0520** [mjdonders/CST816_TouchLib#13]
I've connected cst816 to nrf5340 but touch panel isn't work correctly
Please help me.
Thanks

**Comment by Diddle1** [comment]
I agree because the touchscreen is constantly polling so the nrf5340 or any cc1101 just the transmissions get interrupted they don't even send i've been trying to find a workaround for this and taking me forever to figure it out -.-

**Comment by mjdonders** [comment]
Dear both,
I don't have that setup, so I don't see how I can help here.. The error description provided is also not enough to even try. Please note: polling should not be needed.
I am creating an update for this library for a CST816 based setup with another firmware level and without the reset PIN connected (as-in: the T-Display S3 AMOLED). That chip (firmware) doesn't support the gestures, which I do want. I will add software support for this scenario.
Maybe that will help you out as well.
