### ISSUE TITLE
How to differentiate between simple tap and gesture

### ISSUE THREAD

**Issue by alranel** [mjdonders/CST816_TouchLib#2]
Since `hadTouch()` gets always triggered when a gesture is detected, what is the recommended way to distinguish between a simple tap and a gesture?

Suppose the following scenario: a multi-screen menu with several buttons. In case of a simple tap you want to toggle the pressed button, but in case of a gesture you want to scroll the screen to the next one without activating any button.

(Thank you for this great lib! Much needed.)

**Comment by alranel** [comment]
Maybe it could be useful to dispatch both "down" and "up" touch events? As of now it seems `hadTouch()` only triggers with the "down" event and there's no way to get _when_ and _where_ the finger is released. If the displacement between the "down" location and the "up" location is greater than a constant, one could easily discard the touch event.

**Comment by mjdonders** [comment]
Thanks for the  -Werror=all removal patch: good tip.

About the up/down event: I would if I could..
This library was the best I could do without documentation on the usage of the registers of the CST816.
If you can provide me (a link to) documentation having that level of information I would implement it

**Comment by mjdonders** [comment]
Since this is not an actual issue, but more a feature request (which I currently don't know how to handle based on the lack of documentation), marking this as Closed.
Still very open to receiving the relevant documentation as mentioned above

**Comment by mjdonders** [comment]
As an heads-up: I seem to have managed this.
Please give me some time to release and such: I'm guessing that before the end of the week this is fixed.
(and in the process: I've added double click as well)

**Comment by alranel** [comment]
Thank you for the quick reply!
Meanwhile I found these two resources which seem relevant:

https://github.com/MrMoses1911/TDisplayS3_Touch/blob/master/TDS3_CST816.cpp
https://github.com/levvvy/lilygo-tdisplays3-esphome/blob/main/components/tdisplays3/touchscreen/t_display_s3_touchscreen.cpp

**Comment by mjdonders** [comment]
Thanks. I've used the first as addition to the firmware check.
I had already managed to do the rest yesterday. Please check it and let me know: I think that this was a major improvement
